/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-07-24 03:29:02
*/

module s27
(
  GND,
  VDD,
  CK,
  reset,
  G0,
  G1,
  G17,
  G2,
  G3,
  _20_,
  \_20_.d ,
  _21_,
  \_21_.d ,
  _22_,
  \_22_.d 
);

  input _20_;
  output \_20_.d ;
  input _21_;
  output \_21_.d ;
  input _22_;
  output \_22_.d ;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input CK;
  wire CK;
  wire \DFF_0.D ;
  wire \DFF_0.Q ;
  wire \DFF_1.D ;
  wire \DFF_1.Q ;
  wire \DFF_2.D ;
  wire \DFF_2.Q ;
  input G0;
  wire G0;
  input G1;
  wire G1;
  output G17;
  wire G17;
  input G2;
  wire G2;
  input G3;
  wire G3;
  input GND;
  wire GND;
  input VDD;
  wire VDD;
  input reset;
  wire reset;

  INVX1
  _08_
  (
    .A(reset),
    .Y(_00_)
  );


  INVX1
  _09_
  (
    .A(G0),
    .Y(_03_)
  );


  INVX1
  _10_
  (
    .A(\DFF_0.Q ),
    .Y(_04_)
  );


  NOR2X1
  _11_
  (
    .A(G1),
    .B(\DFF_2.Q ),
    .Y(_05_)
  );


  AND2X1
  _12_
  (
    .A(G3),
    .B(_05_),
    .Y(_06_)
  );


  AOI22X1
  _13_
  (
    .A(_03_),
    .B(\DFF_1.Q ),
    .C(G3),
    .D(_05_),
    .Y(_07_)
  );


  NOR2X1
  _14_
  (
    .A(\DFF_0.Q ),
    .B(_07_),
    .Y(\DFF_1.D )
  );


  OR2X1
  _15_
  (
    .A(\DFF_0.Q ),
    .B(_07_),
    .Y(G17)
  );


  AOI21X1
  _16_
  (
    .A(_04_),
    .B(_06_),
    .C(_03_),
    .Y(\DFF_0.D )
  );


  NOR2X1
  _17_
  (
    .A(G2),
    .B(_05_),
    .Y(\DFF_2.D )
  );


  INVX1
  _18_
  (
    .A(reset),
    .Y(_01_)
  );


  INVX1
  _19_
  (
    .A(reset),
    .Y(_02_)
  );

  assign \DFF_2.Q  = _20_;
  assign \_20_.d  = \DFF_2.D ;
  assign \DFF_1.Q  = _21_;
  assign \_21_.d  = \DFF_1.D ;
  assign \DFF_0.Q  = _22_;
  assign \_22_.d  = \DFF_0.D ;

endmodule

