/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-07-24 03:30:17
*/
`include "tech/osu035/osu035_stdcells.v"
`include "netlists/s298.chain-intermediate.v"


`ifndef CLOCK_PERIOD
    `define CLOCK_PERIOD 4
`endif

module testbench;
    reg[0:0] \reset ;
    reg[0:0] \din ;
    reg[0:0] \sin ;
    wire[0:0] \sout ;
    wire[0:0] \dout ;
    reg[0:0] \testing ;
    reg[0:0] \shift ;
    reg[0:0] \clock ;

        always #(`CLOCK_PERIOD / 2) CK = ~CK; 
        always #(`CLOCK_PERIOD / 2) tck = ~tck; 

    s298 uut(
        .\reset ( \reset ) , .\din ( \din ) , .\sin ( \sin ) , .\sout ( \sout ) , .\dout ( \dout ) , .\testing ( \testing ) , .\shift ( \shift ) , .\clock ( \clock ) 
    ); 

    wire[22:0] __serializable__ =
        23'b00111100000111011110111;
    reg[22:0] __serial__;
    integer i;
    initial begin
        `ifdef VCD
            $dumpfile("chain.vcd");
            $dumpvars(0, testbench);
        `endif
        \din = 0 ;
        \sin = 0 ;
        \clock = 0 ;
        \reset = 0 ;
        \testing = 0 ;
        \shift = 0 ;

        #(`CLOCK_PERIOD*5);
        rst = ~rst;
        shift = 1;
        test = 1;
        for (i = 0; i < 23; i = i + 1) begin
            sin = __serializable__[i];
            #(`CLOCK_PERIOD);
        end
        for (i = 0; i < 23; i = i + 1) begin
            __serial__[i] = sout;
            #(`CLOCK_PERIOD);
        end
        if (__serializable__ === __serial__) begin
            $display("Success: expected %b got %b", __serializable__, __serial__);
            $display("SUCCESS_STRING");
        end else begin
            $display("Failed: expected %b got %b", __serializable__, __serial__);
        end
        $finish;
    end
endmodule
