/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-07-24 03:30:16
*/
/* FAULT METADATA: '{"shift":"shift","boundaryCount":9,"order":[{"ordinal":0,"width":1,"name":"G0","kind":"input"},{"ordinal":0,"width":1,"name":"G1","kind":"input"},{"ordinal":0,"width":1,"name":"G2","kind":"input"},{"ordinal":0,"width":1,"name":"_108_","kind":"dff"},{"ordinal":0,"width":1,"name":"_109_","kind":"dff"},{"ordinal":0,"width":1,"name":"_110_","kind":"dff"},{"ordinal":0,"width":1,"name":"_111_","kind":"dff"},{"ordinal":0,"width":1,"name":"_112_","kind":"dff"},{"ordinal":0,"width":1,"name":"_113_","kind":"dff"},{"ordinal":0,"width":1,"name":"_114_","kind":"dff"},{"ordinal":0,"width":1,"name":"_115_","kind":"dff"},{"ordinal":0,"width":1,"name":"_116_","kind":"dff"},{"ordinal":0,"width":1,"name":"_117_","kind":"dff"},{"ordinal":0,"width":1,"name":"_118_","kind":"dff"},{"ordinal":0,"width":1,"name":"_119_","kind":"dff"},{"ordinal":0,"width":1,"name":"_120_","kind":"dff"},{"ordinal":0,"width":1,"name":"_121_","kind":"dff"},{"ordinal":0,"width":1,"name":"G117","kind":"output"},{"ordinal":0,"width":1,"name":"G118","kind":"output"},{"ordinal":0,"width":1,"name":"G132","kind":"output"},{"ordinal":0,"width":1,"name":"G133","kind":"output"},{"ordinal":0,"width":1,"name":"G66","kind":"output"},{"ordinal":0,"width":1,"name":"G67","kind":"output"}],"sout":"sout","internalCount":14,"sin":"sin"}' END FAULT METADATA */


module BoundaryScanRegister_input
(
  din,
  dout,
  sin,
  sout,
  clock,
  reset,
  testing,
  shift
);

  input din;
  output dout;
  input sin;
  output sout;
  input clock;input reset;input testing;input shift;
  reg store;

  always @(posedge clock or posedge reset) begin
    if(reset) begin
      store <= 1'b0;
    end else begin
      store <= (shift)? sin : dout;
    end
  end

  assign sout = store;
  assign dout = (testing)? store : din;

endmodule



module BoundaryScanRegister_output
(
  din,
  dout,
  sin,
  sout,
  clock,
  reset,
  testing,
  shift
);

  input din;
  output dout;
  input sin;
  output sout;
  input clock;input reset;input testing;input shift;
  reg store;

  always @(posedge clock or posedge reset) begin
    if(reset) begin
      store <= 1'b0;
    end else begin
      store <= (shift)? sin : dout;
    end
  end

  assign sout = store;
  assign dout = din;

endmodule



module \s298.original 
(
  GND,
  VDD,
  CK,
  G0,
  G1,
  G117,
  G118,
  G132,
  G133,
  G2,
  G66,
  G67,
  sin,
  shift,
  sout,
  tck,
  test
);

  input sin;
  output sout;
  input shift;
  input tck;
  input test;
  wire __clk_source__;
  wire __chain_0__;
  assign __chain_0__ = sin;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  input CK;
  wire CK;
  wire \DFF_0.D ;
  wire \DFF_0.Q ;
  wire \DFF_1.D ;
  wire \DFF_1.Q ;
  wire \DFF_10.D ;
  wire \DFF_11.D ;
  wire \DFF_12.D ;
  wire \DFF_12.Q ;
  wire \DFF_13.D ;
  wire \DFF_13.Q ;
  wire \DFF_2.D ;
  wire \DFF_2.Q ;
  wire \DFF_3.D ;
  wire \DFF_3.Q ;
  wire \DFF_4.D ;
  wire \DFF_4.Q ;
  wire \DFF_5.D ;
  wire \DFF_5.Q ;
  wire \DFF_6.D ;
  wire \DFF_7.D ;
  wire \DFF_8.D ;
  wire \DFF_9.D ;
  input G0;
  wire G0;
  input G1;
  wire G1;
  output G117;
  wire G117;
  output G118;
  wire G118;
  output G132;
  wire G132;
  output G133;
  wire G133;
  input G2;
  wire G2;
  output G66;
  wire G66;
  output G67;
  wire G67;
  input GND;
  wire GND;
  input VDD;
  wire VDD;

  INVX1
  _047_
  (
    .A(G0),
    .Y(_000_)
  );


  INVX1
  _048_
  (
    .A(\DFF_4.Q ),
    .Y(_001_)
  );


  INVX1
  _049_
  (
    .A(\DFF_3.Q ),
    .Y(_002_)
  );


  NOR2X1
  _050_
  (
    .A(G0),
    .B(\DFF_0.Q ),
    .Y(\DFF_0.D )
  );


  NOR2X1
  _051_
  (
    .A(\DFF_1.Q ),
    .B(\DFF_2.Q ),
    .Y(_003_)
  );


  OAI21X1
  _052_
  (
    .A(\DFF_0.Q ),
    .B(\DFF_1.Q ),
    .C(_000_),
    .Y(_004_)
  );


  AOI21X1
  _053_
  (
    .A(\DFF_0.Q ),
    .B(\DFF_1.Q ),
    .C(_004_),
    .Y(_005_)
  );


  INVX1
  _054_
  (
    .A(_005_),
    .Y(_006_)
  );


  AOI21X1
  _055_
  (
    .A(\DFF_3.Q ),
    .B(_003_),
    .C(_006_),
    .Y(\DFF_1.D )
  );


  NAND3X1
  _056_
  (
    .A(\DFF_0.Q ),
    .B(\DFF_1.Q ),
    .C(\DFF_2.Q ),
    .Y(_007_)
  );


  AOI21X1
  _057_
  (
    .A(\DFF_0.Q ),
    .B(\DFF_1.Q ),
    .C(\DFF_2.Q ),
    .Y(_008_)
  );


  NOR2X1
  _058_
  (
    .A(G0),
    .B(_008_),
    .Y(_009_)
  );


  AND2X1
  _059_
  (
    .A(_007_),
    .B(_009_),
    .Y(\DFF_2.D )
  );


  NAND2X1
  _060_
  (
    .A(\DFF_0.Q ),
    .B(_003_),
    .Y(_010_)
  );


  AOI21X1
  _061_
  (
    .A(\DFF_0.Q ),
    .B(_003_),
    .C(G0),
    .Y(_011_)
  );


  OAI21X1
  _062_
  (
    .A(_002_),
    .B(_007_),
    .C(_011_),
    .Y(_012_)
  );


  AOI21X1
  _063_
  (
    .A(_002_),
    .B(_007_),
    .C(_012_),
    .Y(\DFF_3.D )
  );


  NAND3X1
  _064_
  (
    .A(\DFF_0.Q ),
    .B(\DFF_3.Q ),
    .C(_003_),
    .Y(_013_)
  );


  NOR2X1
  _065_
  (
    .A(\DFF_13.Q ),
    .B(\DFF_4.Q ),
    .Y(_014_)
  );


  NAND2X1
  _066_
  (
    .A(\DFF_4.Q ),
    .B(\DFF_3.Q ),
    .Y(_015_)
  );


  AOI21X1
  _067_
  (
    .A(\DFF_13.Q ),
    .B(\DFF_4.Q ),
    .C(G0),
    .Y(_016_)
  );


  OAI21X1
  _068_
  (
    .A(_010_),
    .B(_015_),
    .C(_016_),
    .Y(_017_)
  );


  AOI21X1
  _069_
  (
    .A(_013_),
    .B(_014_),
    .C(_017_),
    .Y(\DFF_4.D )
  );


  AND2X1
  _070_
  (
    .A(_001_),
    .B(\DFF_3.Q ),
    .Y(_018_)
  );


  NOR2X1
  _071_
  (
    .A(\DFF_12.Q ),
    .B(\DFF_2.Q ),
    .Y(_019_)
  );


  AND2X1
  _072_
  (
    .A(\DFF_1.Q ),
    .B(_018_),
    .Y(_020_)
  );


  AND2X1
  _073_
  (
    .A(\DFF_12.Q ),
    .B(_003_),
    .Y(_021_)
  );


  AOI21X1
  _074_
  (
    .A(_018_),
    .B(_021_),
    .C(\DFF_5.Q ),
    .Y(_022_)
  );


  AOI21X1
  _075_
  (
    .A(_019_),
    .B(_020_),
    .C(_022_),
    .Y(_023_)
  );


  AND2X1
  _076_
  (
    .A(_000_),
    .B(_023_),
    .Y(\DFF_5.D )
  );


  AOI21X1
  _077_
  (
    .A(\DFF_2.Q ),
    .B(\DFF_4.Q ),
    .C(\DFF_3.Q ),
    .Y(_024_)
  );


  INVX1
  _078_
  (
    .A(_024_),
    .Y(_025_)
  );


  OAI21X1
  _079_
  (
    .A(G66),
    .B(_001_),
    .C(_025_),
    .Y(_026_)
  );


  NOR2X1
  _080_
  (
    .A(_023_),
    .B(_026_),
    .Y(\DFF_6.D )
  );


  AOI21X1
  _081_
  (
    .A(\DFF_4.Q ),
    .B(_003_),
    .C(\DFF_3.Q ),
    .Y(_027_)
  );


  INVX1
  _082_
  (
    .A(_027_),
    .Y(_028_)
  );


  AOI21X1
  _083_
  (
    .A(\DFF_4.Q ),
    .B(\DFF_3.Q ),
    .C(_027_),
    .Y(_029_)
  );


  OR2X1
  _084_
  (
    .A(_023_),
    .B(_029_),
    .Y(_030_)
  );


  NAND3X1
  _085_
  (
    .A(\DFF_1.Q ),
    .B(\DFF_2.Q ),
    .C(_001_),
    .Y(_031_)
  );


  OAI21X1
  _086_
  (
    .A(G67),
    .B(_024_),
    .C(_031_),
    .Y(_032_)
  );


  NOR2X1
  _087_
  (
    .A(_030_),
    .B(_032_),
    .Y(\DFF_7.D )
  );


  NOR2X1
  _088_
  (
    .A(G117),
    .B(_024_),
    .Y(_033_)
  );


  NOR2X1
  _089_
  (
    .A(_030_),
    .B(_033_),
    .Y(\DFF_8.D )
  );


  NAND3X1
  _090_
  (
    .A(\DFF_2.Q ),
    .B(\DFF_4.Q ),
    .C(G118),
    .Y(_034_)
  );


  NOR2X1
  _091_
  (
    .A(G118),
    .B(_015_),
    .Y(_035_)
  );


  NAND2X1
  _092_
  (
    .A(_022_),
    .B(_035_),
    .Y(_036_)
  );


  OAI21X1
  _093_
  (
    .A(_023_),
    .B(_028_),
    .C(_036_),
    .Y(_037_)
  );


  AOI22X1
  _094_
  (
    .A(\DFF_0.Q ),
    .B(_023_),
    .C(_034_),
    .D(_037_),
    .Y(\DFF_9.D )
  );


  OR2X1
  _095_
  (
    .A(\DFF_2.Q ),
    .B(\DFF_3.Q ),
    .Y(_038_)
  );


  OAI21X1
  _096_
  (
    .A(\DFF_2.Q ),
    .B(\DFF_3.Q ),
    .C(G132),
    .Y(_039_)
  );


  OAI21X1
  _097_
  (
    .A(\DFF_1.Q ),
    .B(_038_),
    .C(_039_),
    .Y(_040_)
  );


  AOI21X1
  _098_
  (
    .A(\DFF_4.Q ),
    .B(_040_),
    .C(_023_),
    .Y(_041_)
  );


  AOI21X1
  _099_
  (
    .A(\DFF_0.Q ),
    .B(_023_),
    .C(_041_),
    .Y(\DFF_10.D )
  );


  MUX2X1
  _100_
  (
    .A(G133),
    .B(\DFF_1.Q ),
    .S(\DFF_4.Q ),
    .Y(_042_)
  );


  NOR2X1
  _101_
  (
    .A(\DFF_5.Q ),
    .B(_018_),
    .Y(_043_)
  );


  OAI21X1
  _102_
  (
    .A(\DFF_2.Q ),
    .B(\DFF_3.Q ),
    .C(_043_),
    .Y(_044_)
  );


  NOR2X1
  _103_
  (
    .A(_042_),
    .B(_044_),
    .Y(\DFF_11.D )
  );


  XNOR2X1
  _104_
  (
    .A(\DFF_12.Q ),
    .B(G2),
    .Y(_045_)
  );


  NOR2X1
  _105_
  (
    .A(G0),
    .B(_045_),
    .Y(\DFF_12.D )
  );


  XNOR2X1
  _106_
  (
    .A(\DFF_13.Q ),
    .B(G1),
    .Y(_046_)
  );


  NOR2X1
  _107_
  (
    .A(G0),
    .B(_046_),
    .Y(\DFF_13.D )
  );


  DFFPOSX1
  _108_
  (
    .CLK(__clk_source__),
    .D((shift)? __chain_0__ : \DFF_12.D ),
    .Q(\DFF_12.Q )
  );


  DFFPOSX1
  _109_
  (
    .CLK(__clk_source__),
    .D((shift)? \DFF_12.Q  : \DFF_11.D ),
    .Q(G133)
  );


  DFFPOSX1
  _110_
  (
    .CLK(__clk_source__),
    .D((shift)? G133 : \DFF_13.D ),
    .Q(\DFF_13.Q )
  );


  DFFPOSX1
  _111_
  (
    .CLK(__clk_source__),
    .D((shift)? \DFF_13.Q  : \DFF_8.D ),
    .Q(G117)
  );


  DFFPOSX1
  _112_
  (
    .CLK(__clk_source__),
    .D((shift)? G117 : \DFF_9.D ),
    .Q(G118)
  );


  DFFPOSX1
  _113_
  (
    .CLK(__clk_source__),
    .D((shift)? G118 : \DFF_7.D ),
    .Q(G67)
  );


  DFFPOSX1
  _114_
  (
    .CLK(__clk_source__),
    .D((shift)? G67 : \DFF_10.D ),
    .Q(G132)
  );


  DFFPOSX1
  _115_
  (
    .CLK(__clk_source__),
    .D((shift)? G132 : \DFF_6.D ),
    .Q(G66)
  );


  DFFPOSX1
  _116_
  (
    .CLK(__clk_source__),
    .D((shift)? G66 : \DFF_5.D ),
    .Q(\DFF_5.Q )
  );


  DFFPOSX1
  _117_
  (
    .CLK(__clk_source__),
    .D((shift)? \DFF_5.Q  : \DFF_4.D ),
    .Q(\DFF_4.Q )
  );


  DFFPOSX1
  _118_
  (
    .CLK(__clk_source__),
    .D((shift)? \DFF_4.Q  : \DFF_3.D ),
    .Q(\DFF_3.Q )
  );


  DFFPOSX1
  _119_
  (
    .CLK(__clk_source__),
    .D((shift)? \DFF_3.Q  : \DFF_2.D ),
    .Q(\DFF_2.Q )
  );


  DFFPOSX1
  _120_
  (
    .CLK(__clk_source__),
    .D((shift)? \DFF_2.Q  : \DFF_1.D ),
    .Q(\DFF_1.Q )
  );


  DFFPOSX1
  _121_
  (
    .CLK(__clk_source__),
    .D((shift)? \DFF_1.Q  : \DFF_0.D ),
    .Q(\DFF_0.Q )
  );

  assign sout = \DFF_0.Q ;
  assign __clk_source__ = (test)? tck : CK;

endmodule



module s298
(
  GND,
  VDD,
  CK,
  G0,
  G1,
  G117,
  G118,
  G132,
  G133,
  G2,
  G66,
  G67,
  sin,
  shift,
  sout,
  tck,
  test
);

  input sin;
  output sout;
  input rst;
  input shift;
  input tck;
  input test;
  input CK;
  wire __chain_0__;
  assign __chain_0__ = sin;
  input GND;
  input VDD;
  input G0;
  wire G0__dout;
  wire __chain_1__;

  BoundaryScanRegister_input
  __BoundaryScanRegister_input__0__
  (
    .din(G0),
    .dout(G0__dout),
    .sin(__chain_0__),
    .sout(__chain_1__),
    .clock(tck),
    .reset(rst),
    .testing(test),
    .shift(shift)
  );

  input G1;
  wire G1__dout;
  wire __chain_2__;

  BoundaryScanRegister_input
  __BoundaryScanRegister_input__1__
  (
    .din(G1),
    .dout(G1__dout),
    .sin(__chain_1__),
    .sout(__chain_2__),
    .clock(tck),
    .reset(rst),
    .testing(test),
    .shift(shift)
  );

  input G2;
  wire G2__dout;
  wire __chain_3__;

  BoundaryScanRegister_input
  __BoundaryScanRegister_input__2__
  (
    .din(G2),
    .dout(G2__dout),
    .sin(__chain_2__),
    .sout(__chain_3__),
    .clock(tck),
    .reset(rst),
    .testing(test),
    .shift(shift)
  );

  wire __chain_4__;
  output G117;
  wire G117_din;
  wire __chain_5__;

  BoundaryScanRegister_output
  __BoundaryScanRegister_output__3__
  (
    .din(G117_din),
    .dout(G117),
    .sin(__chain_4__),
    .sout(__chain_5__),
    .clock(tck),
    .reset(rst),
    .testing(test),
    .shift(shift)
  );

  output G118;
  wire G118_din;
  wire __chain_6__;

  BoundaryScanRegister_output
  __BoundaryScanRegister_output__4__
  (
    .din(G118_din),
    .dout(G118),
    .sin(__chain_5__),
    .sout(__chain_6__),
    .clock(tck),
    .reset(rst),
    .testing(test),
    .shift(shift)
  );

  output G132;
  wire G132_din;
  wire __chain_7__;

  BoundaryScanRegister_output
  __BoundaryScanRegister_output__5__
  (
    .din(G132_din),
    .dout(G132),
    .sin(__chain_6__),
    .sout(__chain_7__),
    .clock(tck),
    .reset(rst),
    .testing(test),
    .shift(shift)
  );

  output G133;
  wire G133_din;
  wire __chain_8__;

  BoundaryScanRegister_output
  __BoundaryScanRegister_output__6__
  (
    .din(G133_din),
    .dout(G133),
    .sin(__chain_7__),
    .sout(__chain_8__),
    .clock(tck),
    .reset(rst),
    .testing(test),
    .shift(shift)
  );

  output G66;
  wire G66_din;
  wire __chain_9__;

  BoundaryScanRegister_output
  __BoundaryScanRegister_output__7__
  (
    .din(G66_din),
    .dout(G66),
    .sin(__chain_8__),
    .sout(__chain_9__),
    .clock(tck),
    .reset(rst),
    .testing(test),
    .shift(shift)
  );

  output G67;
  wire G67_din;
  wire __chain_10__;

  BoundaryScanRegister_output
  __BoundaryScanRegister_output__8__
  (
    .din(G67_din),
    .dout(G67),
    .sin(__chain_9__),
    .sout(__chain_10__),
    .clock(tck),
    .reset(rst),
    .testing(test),
    .shift(shift)
  );


  \s298.original 
  __uuf__
  (
    .GND(GND),
    .VDD(VDD),
    .CK(CK),
    .G0(G0__dout),
    .G1(G1__dout),
    .G2(G2__dout),
    .shift(shift),
    .tck(tck),
    .test(test),
    .sin(__chain_3__),
    .sout(__chain_4__),
    .G117(G117_din),
    .G118(G118_din),
    .G132(G132_din),
    .G133(G133_din),
    .G66(G66_din),
    .G67(G67_din)
  );

  assign sout = __chain_10__;

endmodule



