/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-07-24 03:30:21
*/
`include "tech/osu035/osu035_stdcells.v"
`include "netlists/s344.chain-intermediate.v"


`ifndef CLOCK_PERIOD
    `define CLOCK_PERIOD 4
`endif

module testbench;
    reg[0:0] \testing ;
    wire[0:0] \dout ;
    reg[0:0] \reset ;
    reg[0:0] \clock ;
    reg[0:0] \sin ;
    reg[0:0] \shift ;
    reg[0:0] \din ;
    wire[0:0] \sout ;

        always #(`CLOCK_PERIOD / 2) CK = ~CK; 
        always #(`CLOCK_PERIOD / 2) tck = ~tck; 

    s344 uut(
        .\testing ( \testing ) , .\dout ( \dout ) , .\reset ( \reset ) , .\clock ( \clock ) , .\sin ( \sin ) , .\shift ( \shift ) , .\din ( \din ) , .\sout ( \sout ) 
    ); 

    wire[34:0] __serializable__ =
        35'b00011001000000111000101000101101111;
    reg[34:0] __serial__;
    integer i;
    initial begin
        `ifdef VCD
            $dumpfile("chain.vcd");
            $dumpvars(0, testbench);
        `endif
        \din = 0 ;
        \sin = 0 ;
        \clock = 0 ;
        \reset = 0 ;
        \testing = 0 ;
        \shift = 0 ;

        #(`CLOCK_PERIOD*5);
        rst = ~rst;
        shift = 1;
        test = 1;
        for (i = 0; i < 35; i = i + 1) begin
            sin = __serializable__[i];
            #(`CLOCK_PERIOD);
        end
        for (i = 0; i < 35; i = i + 1) begin
            __serial__[i] = sout;
            #(`CLOCK_PERIOD);
        end
        if (__serializable__ === __serial__) begin
            $display("Success: expected %b got %b", __serializable__, __serial__);
            $display("SUCCESS_STRING");
        end else begin
            $display("Failed: expected %b got %b", __serializable__, __serial__);
        end
        $finish;
    end
endmodule
