/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-07-24 03:29:45
*/

module s344
(
  GND,
  VDD,
  CK,
  A0,
  A1,
  A2,
  A3,
  B0,
  B1,
  B2,
  B3,
  CNTVCO2,
  CNTVCON2,
  P0,
  P1,
  P2,
  P3,
  P4,
  P5,
  P6,
  P7,
  READY,
  START,
  _156_,
  \_156_.d ,
  _157_,
  \_157_.d ,
  _158_,
  \_158_.d ,
  _159_,
  \_159_.d ,
  _160_,
  \_160_.d ,
  _161_,
  \_161_.d ,
  _162_,
  \_162_.d ,
  _163_,
  \_163_.d ,
  _164_,
  \_164_.d ,
  _165_,
  \_165_.d ,
  _166_,
  \_166_.d ,
  _167_,
  \_167_.d ,
  _168_,
  \_168_.d ,
  _169_,
  \_169_.d ,
  _170_,
  \_170_.d 
);

  input _156_;
  output \_156_.d ;
  input _157_;
  output \_157_.d ;
  input _158_;
  output \_158_.d ;
  input _159_;
  output \_159_.d ;
  input _160_;
  output \_160_.d ;
  input _161_;
  output \_161_.d ;
  input _162_;
  output \_162_.d ;
  input _163_;
  output \_163_.d ;
  input _164_;
  output \_164_.d ;
  input _165_;
  output \_165_.d ;
  input _166_;
  output \_166_.d ;
  input _167_;
  output \_167_.d ;
  input _168_;
  output \_168_.d ;
  input _169_;
  output \_169_.d ;
  input _170_;
  output \_170_.d ;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  input A0;
  wire A0;
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B0;
  wire B0;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input B3;
  wire B3;
  input CK;
  wire CK;
  output CNTVCO2;
  wire CNTVCO2;
  output CNTVCON2;
  wire CNTVCON2;
  wire \DFF_0.D ;
  wire \DFF_0.Q ;
  wire \DFF_1.D ;
  wire \DFF_1.Q ;
  wire \DFF_10.D ;
  wire \DFF_10.Q ;
  wire \DFF_11.D ;
  wire \DFF_11.Q ;
  wire \DFF_12.D ;
  wire \DFF_12.Q ;
  wire \DFF_13.D ;
  wire \DFF_13.Q ;
  wire \DFF_14.D ;
  wire \DFF_14.Q ;
  wire \DFF_2.D ;
  wire \DFF_2.Q ;
  wire \DFF_3.D ;
  wire \DFF_3.Q ;
  wire \DFF_4.D ;
  wire \DFF_4.Q ;
  wire \DFF_5.D ;
  wire \DFF_5.Q ;
  wire \DFF_6.D ;
  wire \DFF_6.Q ;
  wire \DFF_7.D ;
  wire \DFF_7.Q ;
  wire \DFF_8.D ;
  wire \DFF_8.Q ;
  wire \DFF_9.D ;
  wire \DFF_9.Q ;
  input GND;
  wire GND;
  output P0;
  wire P0;
  output P1;
  wire P1;
  output P2;
  wire P2;
  output P3;
  wire P3;
  output P4;
  wire P4;
  output P5;
  wire P5;
  output P6;
  wire P6;
  output P7;
  wire P7;
  output READY;
  wire READY;
  input START;
  wire START;
  input VDD;
  wire VDD;

  INVX1
  _065_
  (
    .A(\DFF_3.Q ),
    .Y(P7)
  );


  INVX1
  _066_
  (
    .A(\DFF_4.Q ),
    .Y(P6)
  );


  INVX1
  _067_
  (
    .A(\DFF_5.Q ),
    .Y(P5)
  );


  INVX1
  _068_
  (
    .A(\DFF_6.Q ),
    .Y(P4)
  );


  INVX1
  _069_
  (
    .A(\DFF_7.Q ),
    .Y(P3)
  );


  INVX1
  _070_
  (
    .A(\DFF_8.Q ),
    .Y(P2)
  );


  INVX1
  _071_
  (
    .A(\DFF_9.Q ),
    .Y(P1)
  );


  INVX1
  _072_
  (
    .A(\DFF_10.Q ),
    .Y(P0)
  );


  INVX1
  _073_
  (
    .A(\DFF_1.Q ),
    .Y(_029_)
  );


  INVX1
  _074_
  (
    .A(\DFF_11.Q ),
    .Y(_030_)
  );


  INVX1
  _075_
  (
    .A(\DFF_13.Q ),
    .Y(_031_)
  );


  INVX1
  _076_
  (
    .A(\DFF_14.Q ),
    .Y(_032_)
  );


  NAND3X1
  _077_
  (
    .A(\DFF_0.Q ),
    .B(\DFF_2.Q ),
    .C(_029_),
    .Y(_033_)
  );


  INVX1
  _078_
  (
    .A(_033_),
    .Y(READY)
  );


  AND2X1
  _079_
  (
    .A(\DFF_2.Q ),
    .B(\DFF_1.Q ),
    .Y(_034_)
  );


  NAND2X1
  _080_
  (
    .A(\DFF_2.Q ),
    .B(\DFF_1.Q ),
    .Y(_035_)
  );


  AND2X1
  _081_
  (
    .A(\DFF_0.Q ),
    .B(_034_),
    .Y(CNTVCO2)
  );


  INVX1
  _082_
  (
    .A(CNTVCO2),
    .Y(CNTVCON2)
  );


  OR2X1
  _083_
  (
    .A(\DFF_0.Q ),
    .B(\DFF_2.Q ),
    .Y(_036_)
  );


  NOR2X1
  _084_
  (
    .A(\DFF_1.Q ),
    .B(_036_),
    .Y(_037_)
  );


  NOR2X1
  _085_
  (
    .A(READY),
    .B(_037_),
    .Y(_038_)
  );


  OAI21X1
  _086_
  (
    .A(\DFF_1.Q ),
    .B(_036_),
    .C(_033_),
    .Y(_039_)
  );


  NOR3X1
  _087_
  (
    .A(\DFF_6.Q ),
    .B(\DFF_10.Q ),
    .C(_032_),
    .Y(_040_)
  );


  NAND3X1
  _088_
  (
    .A(P4),
    .B(P0),
    .C(\DFF_14.Q ),
    .Y(_041_)
  );


  AOI21X1
  _089_
  (
    .A(P0),
    .B(\DFF_13.Q ),
    .C(P5),
    .Y(_042_)
  );


  OAI21X1
  _090_
  (
    .A(\DFF_10.Q ),
    .B(_031_),
    .C(\DFF_5.Q ),
    .Y(_043_)
  );


  NOR2X1
  _091_
  (
    .A(_040_),
    .B(_043_),
    .Y(_044_)
  );


  NOR3X1
  _092_
  (
    .A(\DFF_5.Q ),
    .B(\DFF_10.Q ),
    .C(_031_),
    .Y(_045_)
  );


  NAND3X1
  _093_
  (
    .A(P5),
    .B(P0),
    .C(\DFF_13.Q ),
    .Y(_046_)
  );


  AOI21X1
  _094_
  (
    .A(_040_),
    .B(_043_),
    .C(_045_),
    .Y(_047_)
  );


  OAI21X1
  _095_
  (
    .A(_041_),
    .B(_042_),
    .C(_046_),
    .Y(_048_)
  );


  AOI21X1
  _096_
  (
    .A(_040_),
    .B(_045_),
    .C(_047_),
    .Y(_049_)
  );


  OAI21X1
  _097_
  (
    .A(_044_),
    .B(_049_),
    .C(_038_),
    .Y(_050_)
  );


  AOI21X1
  _098_
  (
    .A(\DFF_6.Q ),
    .B(_039_),
    .C(START),
    .Y(_051_)
  );


  NAND2X1
  _099_
  (
    .A(_050_),
    .B(_051_),
    .Y(\DFF_6.D )
  );


  NAND2X1
  _100_
  (
    .A(P0),
    .B(\DFF_12.Q ),
    .Y(_052_)
  );


  AOI21X1
  _101_
  (
    .A(P0),
    .B(\DFF_12.Q ),
    .C(P6),
    .Y(_053_)
  );


  NAND2X1
  _102_
  (
    .A(\DFF_4.Q ),
    .B(_052_),
    .Y(_054_)
  );


  NOR2X1
  _103_
  (
    .A(\DFF_4.Q ),
    .B(_052_),
    .Y(_055_)
  );


  OR2X1
  _104_
  (
    .A(\DFF_4.Q ),
    .B(_052_),
    .Y(_056_)
  );


  AOI21X1
  _105_
  (
    .A(_048_),
    .B(_054_),
    .C(_055_),
    .Y(_057_)
  );


  OAI21X1
  _106_
  (
    .A(_047_),
    .B(_053_),
    .C(_056_),
    .Y(_058_)
  );


  OAI21X1
  _107_
  (
    .A(_053_),
    .B(_055_),
    .C(_047_),
    .Y(_059_)
  );


  OAI21X1
  _108_
  (
    .A(_055_),
    .B(_057_),
    .C(_059_),
    .Y(_060_)
  );


  NAND2X1
  _109_
  (
    .A(_038_),
    .B(_060_),
    .Y(_061_)
  );


  AOI21X1
  _110_
  (
    .A(\DFF_5.Q ),
    .B(_039_),
    .C(START),
    .Y(_062_)
  );


  NAND2X1
  _111_
  (
    .A(_061_),
    .B(_062_),
    .Y(\DFF_5.D )
  );


  NOR2X1
  _112_
  (
    .A(\DFF_10.Q ),
    .B(_030_),
    .Y(_063_)
  );


  INVX1
  _113_
  (
    .A(_063_),
    .Y(_064_)
  );


  NOR2X1
  _114_
  (
    .A(_058_),
    .B(_063_),
    .Y(_000_)
  );


  OAI21X1
  _115_
  (
    .A(\DFF_10.Q ),
    .B(_030_),
    .C(_057_),
    .Y(_001_)
  );


  NAND2X1
  _116_
  (
    .A(_058_),
    .B(_063_),
    .Y(_002_)
  );


  OAI21X1
  _117_
  (
    .A(_057_),
    .B(_064_),
    .C(\DFF_3.Q ),
    .Y(_003_)
  );


  AND2X1
  _118_
  (
    .A(_001_),
    .B(_003_),
    .Y(_004_)
  );


  AOI21X1
  _119_
  (
    .A(\DFF_3.Q ),
    .B(_039_),
    .C(START),
    .Y(_005_)
  );


  OAI21X1
  _120_
  (
    .A(_039_),
    .B(_004_),
    .C(_005_),
    .Y(\DFF_3.D )
  );


  AOI21X1
  _121_
  (
    .A(_001_),
    .B(_002_),
    .C(\DFF_3.Q ),
    .Y(_006_)
  );


  OAI21X1
  _122_
  (
    .A(_000_),
    .B(_003_),
    .C(_038_),
    .Y(_007_)
  );


  AOI21X1
  _123_
  (
    .A(\DFF_4.Q ),
    .B(_039_),
    .C(START),
    .Y(_008_)
  );


  OAI21X1
  _124_
  (
    .A(_006_),
    .B(_007_),
    .C(_008_),
    .Y(\DFF_4.D )
  );


  XNOR2X1
  _125_
  (
    .A(\DFF_0.Q ),
    .B(_034_),
    .Y(_009_)
  );


  NOR2X1
  _126_
  (
    .A(START),
    .B(_009_),
    .Y(\DFF_0.D )
  );


  AND2X1
  _127_
  (
    .A(\DFF_2.Q ),
    .B(_033_),
    .Y(_010_)
  );


  OAI21X1
  _128_
  (
    .A(\DFF_1.Q ),
    .B(_010_),
    .C(_035_),
    .Y(_011_)
  );


  NOR2X1
  _129_
  (
    .A(START),
    .B(_011_),
    .Y(\DFF_1.D )
  );


  NOR2X1
  _130_
  (
    .A(START),
    .B(_010_),
    .Y(\DFF_2.D )
  );


  AOI21X1
  _131_
  (
    .A(P0),
    .B(\DFF_14.Q ),
    .C(P4),
    .Y(_012_)
  );


  NAND2X1
  _132_
  (
    .A(B3),
    .B(_033_),
    .Y(_013_)
  );


  OAI21X1
  _133_
  (
    .A(\DFF_7.Q ),
    .B(_033_),
    .C(_013_),
    .Y(_014_)
  );


  OAI21X1
  _134_
  (
    .A(_040_),
    .B(_012_),
    .C(_038_),
    .Y(_015_)
  );


  OAI21X1
  _135_
  (
    .A(_038_),
    .B(_014_),
    .C(_015_),
    .Y(\DFF_7.D )
  );


  NAND2X1
  _136_
  (
    .A(B2),
    .B(_033_),
    .Y(_016_)
  );


  OAI21X1
  _137_
  (
    .A(\DFF_8.Q ),
    .B(_033_),
    .C(_016_),
    .Y(_017_)
  );


  NAND2X1
  _138_
  (
    .A(\DFF_7.Q ),
    .B(_038_),
    .Y(_018_)
  );


  OAI21X1
  _139_
  (
    .A(_038_),
    .B(_017_),
    .C(_018_),
    .Y(\DFF_8.D )
  );


  NAND2X1
  _140_
  (
    .A(B1),
    .B(_033_),
    .Y(_019_)
  );


  OAI21X1
  _141_
  (
    .A(\DFF_9.Q ),
    .B(_033_),
    .C(_019_),
    .Y(_020_)
  );


  NAND2X1
  _142_
  (
    .A(\DFF_8.Q ),
    .B(_038_),
    .Y(_021_)
  );


  OAI21X1
  _143_
  (
    .A(_038_),
    .B(_020_),
    .C(_021_),
    .Y(\DFF_9.D )
  );


  NAND2X1
  _144_
  (
    .A(B0),
    .B(_033_),
    .Y(_022_)
  );


  OAI21X1
  _145_
  (
    .A(\DFF_10.Q ),
    .B(_033_),
    .C(_022_),
    .Y(_023_)
  );


  NAND2X1
  _146_
  (
    .A(\DFF_9.Q ),
    .B(_038_),
    .Y(_024_)
  );


  OAI21X1
  _147_
  (
    .A(_038_),
    .B(_023_),
    .C(_024_),
    .Y(\DFF_10.D )
  );


  MUX2X1
  _148_
  (
    .A(A3),
    .B(\DFF_11.Q ),
    .S(_037_),
    .Y(_025_)
  );


  INVX1
  _149_
  (
    .A(_025_),
    .Y(\DFF_11.D )
  );


  MUX2X1
  _150_
  (
    .A(A2),
    .B(\DFF_12.Q ),
    .S(_037_),
    .Y(_026_)
  );


  INVX1
  _151_
  (
    .A(_026_),
    .Y(\DFF_12.D )
  );


  MUX2X1
  _152_
  (
    .A(A1),
    .B(\DFF_13.Q ),
    .S(_037_),
    .Y(_027_)
  );


  INVX1
  _153_
  (
    .A(_027_),
    .Y(\DFF_13.D )
  );


  MUX2X1
  _154_
  (
    .A(A0),
    .B(\DFF_14.Q ),
    .S(_037_),
    .Y(_028_)
  );


  INVX1
  _155_
  (
    .A(_028_),
    .Y(\DFF_14.D )
  );

  assign \DFF_13.Q  = _156_;
  assign \_156_.d  = \DFF_13.D ;
  assign \DFF_12.Q  = _157_;
  assign \_157_.d  = \DFF_12.D ;
  assign \DFF_14.Q  = _158_;
  assign \_158_.d  = \DFF_14.D ;
  assign \DFF_9.Q  = _159_;
  assign \_159_.d  = \DFF_9.D ;
  assign \DFF_10.Q  = _160_;
  assign \_160_.d  = \DFF_10.D ;
  assign \DFF_8.Q  = _161_;
  assign \_161_.d  = \DFF_8.D ;
  assign \DFF_11.Q  = _162_;
  assign \_162_.d  = \DFF_11.D ;
  assign \DFF_7.Q  = _163_;
  assign \_163_.d  = \DFF_7.D ;
  assign \DFF_6.Q  = _164_;
  assign \_164_.d  = \DFF_6.D ;
  assign \DFF_5.Q  = _165_;
  assign \_165_.d  = \DFF_5.D ;
  assign \DFF_4.Q  = _166_;
  assign \_166_.d  = \DFF_4.D ;
  assign \DFF_3.Q  = _167_;
  assign \_167_.d  = \DFF_3.D ;
  assign \DFF_2.Q  = _168_;
  assign \_168_.d  = \DFF_2.D ;
  assign \DFF_1.Q  = _169_;
  assign \_169_.d  = \DFF_1.D ;
  assign \DFF_0.Q  = _170_;
  assign \_170_.d  = \DFF_0.D ;

endmodule

